name: Linux

on: [push]

jobs:

  ci:
    runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
              submodules: recursive
      - name: Test
        run: |
          bin/init.sh
          export SIREUM_HOME=.
          phantom-ci.cmd